### ISSUE TITLE
Textures/Models

### ISSUE THREAD

**Issue by JacksonHoggard** [CremBluRay/minecraftfeastmod#3]
#### Item textures
* [x] Uncooked turkey meat
* [x] ~Cooked turkey meat~ #7 
* [x] Yeast
* [x] Bread Roll
* [x] Flour
* [x] Dough
* [x] Taco
* [x] Burger
* [x] Corn
* [x] Uncooked bacon
* [x] Cooked bacon
* [x] Pancake

#### Block Models
* [x] Turkey (functions like a cake)

#### Entity Models
* [x] Turkey ~(mob that drops uncooked turkey meat)~ #7

**Comment by Pappy100** [comment]
can i work on this?

**Comment by JacksonHoggard** [comment]
yes
